version: '3.3'

services:
        customer2:
                build: back-end
                container_name: db-customer2
                ports: 
                        - "5433:5432"
                networks:
                        - private_network
networks:
        private_network:
                driver: bridge
