version: '3.3'

services:
        db-postgres:
                build:
                        dockerfile: ./Dockerfile
                        context: ./postgres
                container_name: db-postgres
                ports:
                        - "5433:5432"
                networks:
                        - private_network
        oficina-webapp:
                build:
                        dockerfile: ./Dockerfile
                        context: ./oficina-webapp
                container_name: oficina-app
                ports:
                        - "8080:8080"
                networks:
                        - private_network
networks:
        private_network:
                driver: bridge
