
version: '3.3'

services:
        db-postgres:
                build:
                        dockerfile: ./Dockerfile
                        context: ./postgres
                container_name: db-postgres
                ports:
                        - "5433:5432"
                networks:
                        - overnetwork
        oficina-webapp:
                build:
                        dockerfile: ./Dockerfile
                        context: ./oficina-webapp
                container_name: oficina-app
                ports:
                        - "8080:8080"
                networks:
                        - overnetwork
        cache-order:
                image: redis
                container_name: cache-order
                ports:
                        - "7171:6379"
                networks:
                        - overnetwork
        cache-store:
                image: redis
                container_name: cache-store
                ports:
                        - "7172:6379"
                networks:
                        - overnetwork
        cache-person:
                image: redis
                container_name: cache-person
                ports:
                        - "7173:6379"
                networks:
                        - overnetwork
        cache-customer:
                image: redis
                container_name: cache-customer
                ports:
                        - "7174:6379"
                networks:
                        - overnetwork
networks:
        overnetwork:
                external: true